# Generated by Django 2.2.4 on 2021-05-31 18:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketType', models.CharField(choices=[('中国-韩国', '中国-韩国'), ('韩国-中国', '韩国-中国')], max_length=10, verbose_name='飞机航向')),
                ('airportType', models.CharField(choices=[('大韩航空', '大韩航空'), ('韩亚航空', '韩亚航空'), ('山东航空', '山东航空'), ('青岛航空', '青岛航空'), ('春秋航空', '春秋航空'), ('釜山航空', '釜山航空'), ('中国南方航空', '中国南方航空'), ('韩亚航空', '韩亚航空'), ('中国国际航空', '中国国际航空'), ('中国东方航空', '中国东方航空')], max_length=10, verbose_name='航空公司')),
                ('number', models.CharField(max_length=10, verbose_name='航班号')),
                ('sizeType', models.CharField(choices=[('大型机', '大型机'), ('中型机', '中型机'), ('小型机', '小型机')], max_length=20, verbose_name='机体类型')),
                ('airportModel', models.CharField(max_length=50, verbose_name='飞机型号')),
                ('off', models.CharField(max_length=50, verbose_name='起飞城市')),
                ('offAirport', models.CharField(max_length=50, verbose_name='起飞机场')),
                ('offTime', models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='起飞时间')),
                ('middlePlace', models.CharField(blank=True, max_length=10, null=True, verbose_name='中转城市')),
                ('middleTime', models.CharField(blank=True, max_length=20, null=True, verbose_name='中转时间')),
                ('land', models.CharField(max_length=50, verbose_name='降落城市')),
                ('landAirport', models.CharField(max_length=50, verbose_name='降落机场')),
                ('landTime', models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='降落时间')),
                ('flyTime', models.CharField(max_length=50, verbose_name='飞行时间')),
                ('siteType', models.CharField(choices=[('经济舱', '经济舱'), ('商务舱', '商务舱'), ('头等舱', '头等舱')], max_length=5, verbose_name='座位等级')),
                ('changeType', models.CharField(choices=[('可退改签', '可退改签'), ('不可退改签', '不可退改签')], max_length=10, verbose_name='退改签')),
                ('foodType', models.CharField(choices=[('有餐食', '有餐食'), ('不提供餐食', '不提供餐食')], max_length=10, verbose_name='餐食提供')),
                ('luggageWeight', models.CharField(max_length=30, verbose_name='行李额')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='机票价格')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Ticket/', verbose_name='航空公司标志')),
            ],
        ),
    ]
