# Generated by Django 2.2.4 on 2021-06-01 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('-offTime',), 'verbose_name': '航班', 'verbose_name_plural': '航班'},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='airportModel',
        ),
    ]
