# Generated by Django 2.2.4 on 2021-06-01 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0002_auto_20210601_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='photo',
        ),
    ]
