# Generated by Django 2.2.4 on 2021-06-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0004_auto_20210601_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticketImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(choices=[('大韩航空', '大韩航空'), ('韩亚航空', '韩亚航空'), ('山东航空', '山东航空'), ('青岛航空', '青岛航空'), ('春秋航空', '春秋航空'), ('釜山航空', '釜山航空'), ('中国南方航空', '中国南方航空'), ('韩亚航空', '韩亚航空'), ('中国国际航空', '中国国际航空'), ('中国东方航空', '中国东方航空'), ('济州航空', '济州航空')], max_length=10, verbose_name='航空公司')),
                ('Logo', models.ImageField(blank=True, upload_to='Airport/', verbose_name='航空公司标志')),
            ],
            options={
                'verbose_name': '航空公司logo',
                'verbose_name_plural': '航空公司logo',
            },
        ),
    ]
