# Generated by Django 2.2.4 on 2021-06-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0005_ticketimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketimg',
            name='Code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='航空公司代号'),
        ),
    ]
