# Generated by Django 2.2.4 on 2021-06-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0009_ticket_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='logo',
        ),
    ]
