# Generated by Django 2.2.4 on 2021-06-04 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0011_selfservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketimg',
            name='Code',
        ),
    ]
