# Generated by Django 2.2.4 on 2021-06-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0012_remove_ticketimg_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ticketImg',
        ),
        migrations.AddField(
            model_name='ticket',
            name='logo',
            field=models.ImageField(blank=True, upload_to='Airport/', verbose_name='航空公司标志'),
        ),
    ]
