# Generated by Django 2.2.4 on 2021-06-11 03:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='酒店名字')),
                ('entitle', models.CharField(max_length=50, verbose_name='英文名字')),
                ('score', models.FloatField(max_length=10, verbose_name='酒店评分')),
                ('city', models.CharField(max_length=10, verbose_name='所在城市')),
                ('address', models.CharField(max_length=50, verbose_name='地址')),
                ('checkin', models.CharField(max_length=50, verbose_name='入住时间')),
                ('checkout', models.CharField(max_length=50, verbose_name='离店时间')),
                ('year', models.IntegerField(blank=True, max_length=2021, null=True, verbose_name='建成年份')),
                ('scale', models.CharField(blank=True, max_length=50, null=True, verbose_name='酒店规模')),
                ('near1', models.CharField(blank=True, max_length=20, null=True, verbose_name='附近景点1')),
                ('near2', models.CharField(blank=True, max_length=20, null=True, verbose_name='附近景点2')),
                ('near3', models.CharField(blank=True, max_length=20, null=True, verbose_name='附近景点3')),
                ('method', models.TextField(blank=True, null=True, verbose_name='酒店攻略')),
                ('tip', models.TextField(blank=True, null=True, verbose_name='出行提示')),
                ('main', models.CharField(choices=[('免费wifi', '免费wifi'), ('免费停车场', '免费停车场'), ('电梯', '电梯'), ('餐厅', '餐厅'), ('中文服务', '中文服务'), ('免费瓶装水', '免费瓶装水'), ('吹风机', '吹风机')], max_length=50, verbose_name='主要设施')),
                ('service', models.CharField(choices=[('外币兑换服务', '外币兑换服务'), ('洗衣服务', '洗衣服务'), ('旅游服务', '旅游服务'), ('客房服务', '客房服务'), ('干洗服务', '干洗服务'), ('快速入住服务', '快速入住服务'), ('每日客房清洁', '每日客房清洁'), ('礼宾服务', '礼宾服务'), ('英语', '英语'), ('中文-国语', '中文-国语'), ('日语', '日语'), ('24小时办理入住', '24小时办理入住')], max_length=50, verbose_name='酒店服务')),
                ('hfacility', models.CharField(choices=[('咖啡厅', '咖啡厅'), ('酒吧', '酒吧'), ('健身房', '健身房'), ('商店', '商店')], max_length=50, verbose_name='酒店设施')),
                ('rfacility', models.CharField(choices=[('叫醒服务', '叫醒服务'), ('保险箱', '保险箱'), ('浴衣', '浴衣'), ('浴缸', '浴缸'), ('宽带上网', '宽带上网'), ('空调', '空调'), ('洗漱用品', '洗漱用品'), ('电视', '电视'), ('衣架', '衣架'), ('冰箱', '冰箱'), ('毛巾', '毛巾'), ('拖鞋', '拖鞋'), ('书桌', '书桌'), ('铺设地毯的地板', '铺设地毯的地板'), ('闹钟', '闹钟'), ('电话', '电话')], max_length=50, verbose_name='房间设施')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
            ],
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='用户昵称')),
                ('content', models.TextField(blank=True, null=True, verbose_name='评价内容')),
                ('index', models.IntegerField(blank=True, max_length=5, null=True, verbose_name='评价指数')),
                ('commentDate', models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='发布时间')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userComment', to='hotelApp.Hotel', verbose_name='用户评价')),
            ],
        ),
        migrations.CreateModel(
            name='RoomPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomType', models.CharField(blank=True, max_length=20, null=True, verbose_name='房型')),
                ('roomPeople', models.CharField(blank=True, max_length=20, null=True, verbose_name='可住人数')),
                ('roomPrice', models.CharField(blank=True, max_length=20, null=True, verbose_name='房价')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomPrice', to='hotelApp.Hotel', verbose_name='历史房型房价')),
            ],
        ),
        migrations.CreateModel(
            name='HotelImgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoType', models.CharField(choices=[('外观', '外观'), ('内景', '内景'), ('房间', '房间'), ('环境', '环境'), ('餐厅', '餐厅'), ('其他', '其他')], max_length=50, verbose_name='图片类型')),
                ('photo', models.ImageField(blank=True, max_length=6, upload_to='Hotel/Comment/', verbose_name='评价图片')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotelImgs', to='hotelApp.Hotel', verbose_name='酒店图片')),
            ],
        ),
        migrations.CreateModel(
            name='CommentImgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, max_length=6, upload_to='Hotel/Comment/', verbose_name='评价图片')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userImgs', to='hotelApp.UserComment', verbose_name='评价图片')),
            ],
        ),
    ]
