# Generated by Django 2.2.4 on 2021-06-11 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0002_auto_20210611_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentImgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, max_length=6, upload_to='Hotel/Comment/', verbose_name='评价图片')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userImgs', to='hotelApp.UserComment', verbose_name='评价图片')),
            ],
        ),
    ]
