# Generated by Django 2.2.4 on 2021-06-11 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0004_auto_20210611_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercomment',
            options={},
        ),
        migrations.DeleteModel(
            name='CommentImgs',
        ),
    ]
