# Generated by Django 2.2.4 on 2021-06-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0005_auto_20210611_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilities', models.CharField(max_length=20, verbose_name='设施内容')),
            ],
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='main',
        ),
    ]
