# Generated by Django 2.2.4 on 2021-06-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0006_auto_20210611_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='mfacility',
            field=models.ManyToManyField(to='hotelApp.MainFacility', verbose_name='主要设施'),
        ),
    ]
