# Generated by Django 2.2.4 on 2021-06-11 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0007_hotel_mfacility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainfacility',
            options={'verbose_name': '主要设施', 'verbose_name_plural': '主要设施'},
        ),
    ]
