# Generated by Django 2.2.4 on 2021-06-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0008_auto_20210611_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilities', models.CharField(max_length=20, verbose_name='酒店设施')),
            ],
            options={
                'verbose_name': '酒店设施',
                'verbose_name_plural': '酒店设施',
            },
        ),
        migrations.CreateModel(
            name='RoomFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilities', models.CharField(max_length=20, verbose_name='房间设施')),
            ],
            options={
                'verbose_name': '房间设施',
                'verbose_name_plural': '房间设施',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilities', models.CharField(max_length=20, verbose_name='酒店服务')),
            ],
            options={
                'verbose_name': '酒店服务',
                'verbose_name_plural': '酒店服务',
            },
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hfacility',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='rfacility',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='service',
        ),
        migrations.AddField(
            model_name='hotel',
            name='hfacility',
            field=models.ManyToManyField(to='hotelApp.HotelFacility', verbose_name='酒店设施'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='rfacility',
            field=models.ManyToManyField(to='hotelApp.RoomFacility', verbose_name='房间设施'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='service',
            field=models.ManyToManyField(to='hotelApp.Service', verbose_name='酒店服务'),
        ),
    ]
