# Generated by Django 2.2.4 on 2021-06-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0009_auto_20210611_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimgs',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Hotel/Comment/', verbose_name='评价图片'),
        ),
    ]
