# Generated by Django 2.2.4 on 2021-06-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='Home/Img/', verbose_name='首页轮播图片')),
            ],
            options={
                'verbose_name': '首页图片',
                'verbose_name_plural': '首页图片',
            },
        ),
    ]
