# Generated by Django 2.2.4 on 2021-06-04 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='昵称')),
                ('phone', models.CharField(max_length=20, verbose_name='电话号码')),
                ('email', models.EmailField(max_length=30, verbose_name='邮箱')),
                ('title', models.CharField(max_length=40, verbose_name='留言标题')),
                ('content', models.CharField(max_length=200, verbose_name='留言内容')),
                ('publishDate', models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='提交时间')),
                ('replycontent', models.TextField(blank=True, null=True, verbose_name='回复')),
                ('replyDate', models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='回复时间')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
                'ordering': ['-replyDate'],
            },
        ),
    ]
