# Generated by Django 2.2.4 on 2021-06-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageApp', '0002_protocol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protocol',
            options={'ordering': ['-publishDate'], 'verbose_name': '协议', 'verbose_name_plural': '协议'},
        ),
        migrations.AddField(
            model_name='protocol',
            name='file',
            field=models.FileField(blank=True, upload_to='Protocol/', verbose_name='协议资料'),
        ),
    ]
