# Generated by Django 2.2.4 on 2021-06-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageApp', '0003_auto_20210605_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='简称'),
        ),
    ]
