# Generated by Django 2.2.4 on 2021-06-09 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
