# Generated by Django 2.2.4 on 2021-06-09 02:25

import DjangoUeditor.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('noteApp', '0002_delete_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlephoto', models.ImageField(blank=True, null=True, upload_to='note/', verbose_name='头图')),
                ('title', models.CharField(max_length=50, verbose_name='游记标题')),
                ('author', models.CharField(default='匿名', max_length=10, null=True, verbose_name='作者')),
                ('tripDate', models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='出游时间')),
                ('days', models.CharField(max_length=10, null=True, verbose_name='出游天数')),
                ('people', models.CharField(max_length=20, null=True, verbose_name='人物')),
                ('price', models.CharField(max_length=10, null=True, verbose_name='平均消费')),
                ('description', DjangoUeditor.models.UEditorField(default='', verbose_name='内容')),
                ('publishDate', models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='发布时间')),
                ('views', models.PositiveSmallIntegerField(default=0, verbose_name='浏览量')),
            ],
            options={
                'verbose_name': '游记',
                'verbose_name_plural': '游记',
                'ordering': ['-publishDate'],
            },
        ),
    ]
