# Generated by Django 2.2.4 on 2021-06-09 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteApp', '0003_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
