# Generated by Django 2.2.4 on 2021-06-09 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteApp', '0007_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
