# Generated by Django 2.2.4 on 2021-06-12 09:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('title', models.CharField(max_length=40, verbose_name='留言标题')),
                ('content', models.TextField(verbose_name='留言内容')),
                ('quizDate', models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '问答',
                'verbose_name_plural': '问答',
                'ordering': ('-quizDate',),
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='攻略名称')),
                ('file', models.FileField(blank=True, upload_to='Strategy/', verbose_name='攻略资料')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='攻略描述')),
                ('photo', models.ImageField(blank=True, upload_to='Strategy/Img/', verbose_name='封面图片')),
                ('publishDate', models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '攻略',
                'verbose_name_plural': '攻略',
                'ordering': ['-publishDate'],
            },
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='签证名称')),
                ('city', models.CharField(max_length=20, verbose_name='城市')),
                ('type', models.CharField(max_length=20, verbose_name='签证类型')),
                ('expire', models.CharField(max_length=20, verbose_name='有效期')),
                ('staydays', models.CharField(max_length=20, verbose_name='停留天数')),
                ('number', models.CharField(max_length=20, verbose_name='入境次数')),
                ('order', models.CharField(max_length=20, verbose_name='订单有效期')),
                ('place', models.CharField(max_length=100, verbose_name='受理地区')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('discount', models.CharField(max_length=100, verbose_name='优惠信息')),
                ('discountprice', models.IntegerField(verbose_name='优惠价格')),
                ('orderknow', models.CharField(max_length=100, verbose_name='预订须知')),
                ('slogan', models.ImageField(blank=True, upload_to='Visa/', verbose_name='封面图片')),
                ('flow', models.ImageField(blank=True, upload_to='Visa/', verbose_name='办签流程')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='取消政策')),
                ('tip', models.TextField(blank=True, max_length=500, null=True, verbose_name='温馨提示')),
                ('tips', models.TextField(blank=True, max_length=500, null=True, verbose_name='重要提示')),
                ('message', models.TextField(blank=True, max_length=500, null=True, verbose_name='产品服务信息')),
                ('views', models.PositiveIntegerField(default=50, verbose_name='浏览量')),
            ],
            options={
                'verbose_name': '签证',
                'verbose_name_plural': '签证',
            },
        ),
        migrations.CreateModel(
            name='visaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.CharField(choices=[('在职人员', '在职人员'), ('自由职业', '自由职业'), ('在校学生', '在校学生'), ('退休人员', '退休人员'), ('学龄前儿童', '学龄前儿童')], max_length=10, verbose_name='人员类型')),
                ('data', models.CharField(max_length=10, verbose_name='材料名称')),
                ('type', models.CharField(max_length=10, verbose_name='材料类型')),
                ('amount', models.IntegerField(verbose_name='材料数量')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='材料说明')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='communityApp.Visa', verbose_name='签证名称')),
            ],
            options={
                'verbose_name': '所需材料',
                'verbose_name_plural': '所需材料',
            },
        ),
        migrations.CreateModel(
            name='visaAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.ImageField(blank=True, upload_to='Visa/', verbose_name='产品介绍')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abouts', to='communityApp.Visa', verbose_name='签证名称')),
            ],
            options={
                'verbose_name': '产品介绍',
                'verbose_name_plural': '产品介绍',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replyname', models.CharField(max_length=20, verbose_name='姓名')),
                ('replycontent', models.TextField(verbose_name='回复')),
                ('replyDate', models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='回复时间')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replys', to='communityApp.Quiz', verbose_name='回复')),
            ],
            options={
                'verbose_name': '问题回复',
                'verbose_name_plural': '问题回复',
            },
        ),
    ]
