# Generated by Django 2.2.4 on 2021-05-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='城市名字')),
                ('enname', models.CharField(max_length=40, verbose_name='城市罗马音')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='城市描述')),
                ('photo', models.ImageField(blank=True, upload_to='City/', verbose_name='城市照片')),
            ],
        ),
    ]
