# Generated by Django 2.2.4 on 2021-05-29 14:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('destinationApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='特色标题')),
                ('kname', models.CharField(max_length=20, verbose_name='韩文名字')),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='特色评分')),
                ('description', models.TextField(max_length=300, verbose_name='特色详情描述')),
                ('traffic', models.TextField(verbose_name='交通路线')),
                ('productType', models.CharField(choices=[('景点', '景点'), ('娱乐', '娱乐'), ('美食', '美食')], max_length=50, verbose_name='特色类型')),
                ('publishDate', models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='发布时间')),
                ('comment1', models.TextField(max_length=300, verbose_name='精选点评1')),
                ('Date1', models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='点评时间1')),
                ('comment2', models.TextField(max_length=300, verbose_name='精选点评2')),
                ('Date2', models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='点评时间2')),
                ('comment3', models.TextField(max_length=300, verbose_name='精选点评3')),
                ('Date3', models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='点评时间3')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
            ],
            options={
                'verbose_name': '特色',
                'verbose_name_plural': '特色',
                'ordering': ('-publishDate',),
            },
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': '热门城市', 'verbose_name_plural': '热门城市'},
        ),
        migrations.CreateModel(
            name='SpecialImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='Special/', verbose_name='特色照片')),
                ('special', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialImgs', to='destinationApp.Special', verbose_name='特色')),
            ],
            options={
                'verbose_name': '特色图片',
                'verbose_name_plural': '特色图片',
            },
        ),
    ]
