# Generated by Django 2.2.4 on 2021-05-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinationApp', '0003_auto_20210529_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='open',
            field=models.TextField(blank=True, null=True, verbose_name='开放时间'),
        ),
        migrations.AddField(
            model_name='special',
            name='tickets',
            field=models.TextField(blank=True, null=True, verbose_name='门票'),
        ),
        migrations.AlterField(
            model_name='special',
            name='comment1',
            field=models.TextField(max_length=500, verbose_name='精选点评1'),
        ),
        migrations.AlterField(
            model_name='special',
            name='comment2',
            field=models.TextField(max_length=500, verbose_name='精选点评2'),
        ),
        migrations.AlterField(
            model_name='special',
            name='comment3',
            field=models.TextField(max_length=500, verbose_name='精选点评3'),
        ),
        migrations.AlterField(
            model_name='special',
            name='description',
            field=models.TextField(max_length=500, verbose_name='特色详情描述'),
        ),
        migrations.AlterField(
            model_name='special',
            name='traffic',
            field=models.TextField(blank=True, null=True, verbose_name='交通路线'),
        ),
    ]
