# Generated by Django 2.2.4 on 2021-05-31 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinationApp', '0008_city_views'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CityImg',
        ),
    ]
